### ISSUE TITLE
Plugin doens't work.

### ISSUE THREAD

**Issue by ghost** [haoruan/HDT-Reconnector#12]
Hi. The plugin doens't disconnect my game when I click the buttom. I'm sure I followed every instruction. I have no idea why this happens.

**Comment by haoruan** [comment]
Will check

**Comment by haoruan** [comment]
Hey, can you try it again and share the log (`%AppData%/HearthstoneDeckTracker/Logs/hdt_log.txt`)?

**Comment by ghost** [comment]
[hdt_log.txt](https://github.com/haoruan/HDT-Reconnector/files/9994828/hdt_log.txt)

**Comment by haoruan** [comment]
Thanks, sounds like it can't get any network connection of Hearthstone.
I upload a new version [v.1.4.3-log](https://github.com/haoruan/HDT-Reconnector/releases/tag/v1.4.3-log) to dump more logs, can you try it again and also share the log?

**Comment by ghost** [comment]
[hdt_log.txt](https://github.com/haoruan/HDT-Reconnector/files/10013884/hdt_log.txt)

Here it is. FYI, I just find it works for my CN regional account and it doesn't work for my US regional account.

**Comment by haoruan** [comment]
Are you using any VPN? The TCP connection of hearthstone is to 127.0.0.1, so the plugin can't find the correct server connection.

**Comment by guqiyao** [comment]
那如果用了代理有什么办法能拔线么..

**Comment by haoruan** [comment]
> 那如果用了代理有什么办法能拔线么..

理论上可以断开炉石的所有tcp连接，或者特定端口的连接，但稳定性未知
