### ISSUE TITLE
Game concedes sometimes when I press the reconnect button

### ISSUE THREAD

**Issue by Smellyheadz** [haoruan/HDT-Reconnector#16]
I've had this occur on numerous occasions. I'll push the reconnect button and the game will freeze and won't reconnect. Attempting to restart the client doesn't let me back into the game and shows me at X place in my full stats page indicating the game has completed.

I've had this happen a couple of times whilst people have been spectating me and they show me as winning the fight and then instantly conceding the game. 

Let me know if you need any files/logs etc etc  to investigate the issue or if you have any tips on how I might be able to stop this occurring.

**Comment by haoruan** [comment]
I'm not sure if the log helps, but please share the log (%AppData%/HearthstoneDeckTracker/Logs/hdt_log.txt), so I can check it. Please use [v.1.4.3-log](https://github.com/haoruan/HDT-Reconnector/releases/tag/v1.4.3-log), it dumps more logs.

Functionally, this plugin just resets the hearthstone internet connection and won't touch any game mechanism. So it must be hearthstone's decision/bug.

I don't really know how hearthstone decides the concede in disconnection, but the only case I know is disconnecting after a certain time will be treated as conceding.

I'm also wondering if this happened when you're disconnected from the game normally, for example turning the router off and on, or in an unstable connection, or the game crashed?

Btw, are you using Win11? I didn't test it in Win11, so maybe it's the other reason. And have you tried to reinstall Hearthstone, it may help in some cases.

**Comment by Smellyheadz** [comment]
![image](https://user-images.githubusercontent.com/120309454/207010438-309f084c-ba86-41cb-8cf5-f6c39f0898a5.png)
![image](https://user-images.githubusercontent.com/120309454/207010498-654d6e5b-ae14-40d5-9968-648b959cabef.png)
It just happened again. Here's the screenshot of trying to reconnect showing i had a 100% win chance with no lethal and the result of the game in my last 5 warbands straight after. 
Here's a log as well. This wasn't done using the 1.4.3-log, but i'll install/try that again.
[hdt_logConcede.txt](https://github.com/haoruan/HDT-Reconnector/files/10206606/hdt_logConcede.txt)
I'm on win10, not 11. 
Haven't tried reinstall hearthstone, but I can.

**Comment by shepardz322** [comment]
just registered to post that these sudden concedes are not a myth, happens to me way too much last days. usually when not many people left, this is sad because the plugin itself is a bomb

**Comment by shepardz322** [comment]
and these are not "concedes" in a common way, the game thinks that u left and makes u leave the lobby,

"I'm also wondering if this happened when you're disconnected from the game normally, for example turning the router off and on, or in an unstable connection, or the game crashed?"
 for me it happens when i press the reconnect button and then game freezes and after relog manually the game is over

**Comment by haoruan** [comment]
Thanks for the details.
Maybe Hearthstone updates its code recently to stop users from using disconnection to skip battle, I'll test it.

**Comment by haoruan** [comment]
Did you disconnect too many times in a match? >10?
One issue I know is if you disconnected over 10 times (I don't remember the exact number) in a match, the next disconnect will be treated as a concede.

**Comment by shepardz322** [comment]
> 

thx, sounds like that's what it is
