### ISSUE TITLE
Reconnect button gone after latest HS deck tracker update (31st of May 2023)

### ISSUE THREAD

**Issue by Lunco** [haoruan/HDT-Reconnector#19]
Reconnect button no longer shows up. Tried resetting the overlay, doesn't work. I reinstalled the whole thing and deleted the appdata folder and it did not fix. I'm on Windows 11, if it matters. 

Anyone else with this issue?

**Comment by Restartedat0** [comment]
> Reconnect button no longer shows up. Tried resetting the overlay, doesn't work. I reinstalled the whole thing and deleted the appdata folder and it did not fix. I'm on Windows 11, if it matters.
> 
> Anyone else with this issue?

Same issue here.

**Comment by haoruan** [comment]
Thanks for the report, will check

**Comment by chiefycat23** [comment]
this ish doesnt work NO MORE B! Pls fix my brain is gonna dieeee
