### ISSUE TITLE
Reconnect button displaces "what to mulligan" button in constructed play

### ISSUE THREAD

**Issue by Lunco** [haoruan/HDT-Reconnector#22]
Not exactly completely sure the extension is the cause, but I'm kinda guessing it is. The "what to mulligan" button from the base application gets pushed down below the windows start toolbar. Could you add an option to disable the extension in constructed play?

**Comment by haoruan** [comment]
You can disable the plugin at here:
![hdt](https://github.com/haoruan/HDT-Reconnector/assets/6285933/a55b777a-56f3-43fb-83af-389c7a8c424d)
