### ISSUE TITLE
Ability to move the reconnect overlay button element?

### ISSUE THREAD

**Issue by nmpsyntax** [haoruan/HDT-Reconnector#7]
The current position of the reconnect button collides with other plugins. How about the ability to move and maybe resize the button like other overlay elements within HDT?

**Comment by haoruan** [comment]
make sense, working on it

**Comment by nmpsyntax** [comment]
Wow, you're so fast! I'd love to test it out with a new release if you're ready.

**Comment by haoruan** [comment]
Feel free to have a try!

**Comment by nmpsyntax** [comment]
Great work 🥇!
